const DISTRICT_MAPPING = {
  'EAST': 1,
  'WEST': 2,
  'NORTH': 3,
  'SOUTH': 4
}

const OWNERSHIP_MAPPING = {
  'JOINT': 1,
  'INDIVIDUAL': 2
}

const REVIEWER_ID_MAPPING = {
  'HEM CHAND': 1460,
  'SUDHANSHU GUPTA': 1311,
  'RAHUL SINGH': 2456,
  'MANOJ PANDEY': 1678,
  'VINOD GUPTA': 4510
}

const CATEGORY_ID_MAPPING = {
  'COMMERICAL': 1,
  'RESIDENTIAL': 2,
}

const STATUS_ID_MAPPING = {
  'APPROVED': 1,
  'PENDING': 2,
  'CONNECTION RELEASED': 3,
  'REJECTED': 4,
}

const BASE_URL = 'http://localhost:8000/api'


export {
  DISTRICT_MAPPING,
  OWNERSHIP_MAPPING,
  BASE_URL,
  REVIEWER_ID_MAPPING,
  CATEGORY_ID_MAPPING,
  STATUS_ID_MAPPING
}