# Generated by Django 4.1.3 on 2022-11-19 09:17

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Applicant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('gender', models.CharField(max_length=10)),
                ('pincode', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='ConnectionCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='ConnectionStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='GovtIdType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Ownership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Reviewer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reviewer_id', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('name', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='State',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='District',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('state', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='electricity_board.state')),
            ],
        ),
        migrations.CreateModel(
            name='ConnectionApplicationRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('govt_id_number', models.CharField(max_length=20)),
                ('load_applied', models.PositiveIntegerField(blank=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(200)])),
                ('applied_on', models.DateField()),
                ('approved_on', models.DateField(blank=True, default=None, null=True)),
                ('updated_at', models.DateField()),
                ('active', models.BooleanField(default=True)),
                ('comment', models.CharField(max_length=250)),
                ('applicant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='electricity_board.applicant')),
                ('connection_category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='electricity_board.connectioncategory')),
                ('govt_id_used', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='electricity_board.govtidtype')),
                ('reviewer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='electricity_board.reviewer')),
                ('status', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='electricity_board.connectionstatus')),
            ],
        ),
        migrations.AddField(
            model_name='applicant',
            name='district',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='electricity_board.district'),
        ),
        migrations.AddField(
            model_name='applicant',
            name='ownership',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='electricity_board.ownership'),
        ),
        migrations.AddField(
            model_name='applicant',
            name='state',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='electricity_board.state'),
        ),
    ]
