# Generated by Django 4.1.3 on 2022-11-19 09:29

from django.db import migrations

def seed_state(apps, schema_editor):
  State = apps.get_model('electricity_board', 'State')
  state = State(name='Delhi'.upper())
  state.save()

def reverse_func(apps, schema_editor):
  pass

class Migration(migrations.Migration):

    dependencies = [
        ('electricity_board', '0001_initial'),
    ]

    operations = [
      migrations.RunPython(seed_state, reverse_func),
    ]
