# Generated by Django 4.1.3 on 2022-11-19 09:32

from django.db import migrations

def seed_districts(apps, schema_editor):
  District = apps.get_model('electricity_board', 'District')
  State = apps.get_model('electricity_board', 'State')
  districts = ['East', 'West', 'North', 'South']
  state = State.objects.get(pk=1)
  for district in districts:
    new_district = District(name=district.upper(), state=state)
    new_district.save()

def reverse_func(apps, schema_editor):
  pass

class Migration(migrations.Migration):

    dependencies = [
        ('electricity_board', '0002_auto_20221119_1459'),
    ]

    operations = [
      migrations.RunPython(seed_districts, reverse_func)
    ]
