# Generated by Django 4.1.3 on 2022-11-19 09:32

from django.db import migrations

def seed_connection_status(apps, schema_editor):
  ConnectionStatus = apps.get_model('electricity_board', 'ConnectionStatus')
  connection_statuses = ['Approved', 'Pending', 'Connection Released', 'Rejected ']
  for status in connection_statuses:
    new_status = ConnectionStatus(status=status.upper())
    new_status.save()

def reverse_func(apps, schema_editor):
  pass

class Migration(migrations.Migration):

    dependencies = [
        ('electricity_board', '0003_auto_20221119_1502'),
    ]

    operations = [
      migrations.RunPython(seed_connection_status, reverse_func)
    ]
