# Generated by Django 4.1.3 on 2022-11-19 09:33

from django.db import migrations

def seed_connection_category(apps, schema_editor):
  ConnectionCategory = apps.get_model('electricity_board', 'ConnectionCategory')
  connection_categories = ['Commerical', 'Residential']
  for cateogry in connection_categories:
    new_cateogry = ConnectionCategory(category=cateogry.upper())
    new_cateogry.save()

def reverse_func(apps, schema_editor):
  pass

class Migration(migrations.Migration):

    dependencies = [
        ('electricity_board', '0004_auto_20221119_1502'),
    ]

    operations = [
      migrations.RunPython(seed_connection_category, reverse_func)
    ]
