# Generated by Django 4.1.3 on 2022-11-19 09:34

from django.db import migrations

def seed_govt_id_types(apps, schema_editor):
  GovtIdType = apps.get_model('electricity_board', 'GovtIdType')
  govt_id_types = ['AADHAR', 'VOTER_ID', 'PAN', 'PASSPORT']
  for id_type in govt_id_types:
    govt_id_type = GovtIdType(type=id_type)
    govt_id_type.save()

def reverse_func(apps, schema_editor):
  pass

class Migration(migrations.Migration):

    dependencies = [
        ('electricity_board', '0005_auto_20221119_1503'),
    ]

    operations = [
      migrations.RunPython(seed_govt_id_types, reverse_func)
    ]
