# Generated by Django 4.1.3 on 2022-11-19 09:34

from django.db import migrations

def seed_ownerships(apps, schema_editor):
  Ownership = apps.get_model('electricity_board', 'Ownership')
  ownership_types = ['JOINT', 'INDIVIDUAL']
  for type in ownership_types:
    ownership_type = Ownership(type=type)
    ownership_type.save()

def reverse_func(apps, schema_editor):
  pass

class Migration(migrations.Migration):

    dependencies = [
        ('electricity_board', '0006_auto_20221119_1504'),
    ]

    operations = [
      migrations.RunPython(seed_ownerships, reverse_func)
    ]
